### ISSUE TITLE
Can´t get 100% of sync, no successful proposals

### ISSUE THREAD

**Issue by CryptoWanny** [aptos-labs/aptos-ait3#14]
When my node has 99% of sync it gets stuck. Even after restart it stuck again right before it gets 100%. All updates done.
I tried to restart it deleting Data Volume, the issue still present.

REWARDS PERFORMANCE - 0 , proposals number - 0

I´m using virtual server:

10 cores CPU
RAM 60 GB
2000 GB of Disk

Ubuntu 20.04
Current commit is 4219d75c57115805f0faf0ad07c17becf6580202

Located in Germany

[logs AIT3.txt](https://github.com/aptos-labs/aptos-ait3/files/9465771/logs.AIT3.txt)

**Comment by CryptoWanny** [comment]
I´m using virtual server:
10 cores CPU 
RAM 60 GB
2000 GB of Disk
1Gbps connection
Ubuntu 20.04 
Located in Germany

**Comment by JoshLind** [comment]
Thanks @CryptoWanny! What's your owner address? 😄

**Comment by JoshLind** [comment]
Also, could you please attach more logs?

**Comment by CryptoWanny** [comment]
@JoshLind, thank you for reply

My owner wallet is 0xf758b0bf7a9bfb700b84b83779bb92ef8d7a4c22587bf7a05481abd77713df65

More logs are here, hope that will help to find out the reason of issue

thanks
[logfile500.txt](https://github.com/aptos-labs/aptos-ait3/files/9467637/logfile500.txt)

**Comment by CryptoWanny** [comment]
![image](https://user-images.githubusercontent.com/79758108/187867747-6048a27e-5521-4af8-bb21-fd7f6993780a.png)

**Comment by CryptoWanny** [comment]
![image](https://user-images.githubusercontent.com/79758108/188078885-5db3e199-fbed-4f5d-926f-a35d01543b3d.png)
 My node is on this list, but the fix doesn´t work for my case. I checked, my validator-identity.yaml  contains account_address, security data deleted.

**Comment by CryptoWanny** [comment]
[logfile500-2.txt](https://github.com/aptos-labs/aptos-ait3/files/9476504/logfile500-2.txt)
 New log file after restart from 0

**Comment by lenkazaiakova** [comment]
> Tried to fix it once again last night Steps done:
> 
> * checked validator-identity.yaml, checked that the wallet field contains correct data
> * deleted db and secure-data.json
> * rebooted (took around 10 hrs for 99% sync)
> 
> The problem is still the same
> 
> New logs attached
> 
> [logfile500-2.txt](https://github.com/aptos-labs/aptos-ait3/files/9476504/logfile500-2.txt)

I have the same problem, and the same server specs (contabo XL VPS).
Node resyncing solved the problem for ~5 hours, and then the problem returned.

**Comment by CryptoWanny** [comment]
My node was already fine before the last upgrade (testnet_26ed95ce4c8798743e7900bba566d29079af0a70), I had 2 proposals. After the last upgrade I lost sync again and can´t reach it

**Comment by CryptoWanny** [comment]
After upgrade **testnet_88f936bf40a56768e2dac420e953a0307281c1ba** my node finally started to make proposals. 
So far everything looks good, will update you if something.

New Logs attached


![image](https://user-images.githubusercontent.com/79758108/188289104-7e2b4add-2710-4abb-ad3b-b69eb6c5dffb.png)

[logfile6.txt](https://github.com/aptos-labs/aptos-ait3/files/9483462/logfile6.txt)

**Comment by CryptoWanny** [comment]
My node is getting a lot of failed proposals

![image](https://user-images.githubusercontent.com/79758108/188425044-73526083-244a-409f-8bcc-ebbfc51ec1e9.png)
