### ISSUE TITLE
[BUG] [Wallet] different "locked until"

### ISSUE THREAD

**Issue by Nelrann** [aptos-labs/aptos-ait3#2]
Hello,
It seems like "locked until" is different between wallet and https://explorer.devnet.aptos.dev/proposals/staking

![image](https://user-images.githubusercontent.com/503587/187385122-a1f85c71-d069-45f0-a08a-536041de0afd.png)

**Comment by hariria** [comment]
@Nelrann hey could you add which account address this was for so I can reproduce it?

**Comment by hoanngothanh** [comment]
same here 
![Screen Shot 2022-08-31 at 02 03 17](https://user-images.githubusercontent.com/7513768/187521168-f3b5ea8a-78db-4e87-a12a-18c760dee083.png)

**Comment by hoanngothanh** [comment]
My voter address 0x454ae62855c24140f39398de478b49ac53dd072edea2b54f07d272c9008ddc12
@hariria

**Comment by sherry-x** [comment]
team is working on fixing this now, thanks for reporting!

**Comment by Nelrann** [comment]
> @Nelrann hey could you add which account address this was for so I can reproduce it?

sry for delay 
my address : 0x62562701d5f396a2f8e7bc44e8700214d0cbc38c46d78dbf9dcab949f1dec6c5

**Comment by Nelrann** [comment]
sry for delay @hariria 

address : 0x62562701d5f396a2f8e7bc44e8700214d0cbc38c46d78dbf9dcab949f1dec6c5

**Comment by hariria** [comment]
Hi, thanks for reporting the bug, I've gone ahead and fixed it. It's not available in the most recent chrome store update but hopefully should be available in our next release. For now please go with the explorer locked_until :)
