### ISSUE TITLE
Node stop synchronizing

### ISSUE THREAD

**Issue by nodtechee** [aptos-labs/aptos-ait3#22]
Node stop synchronizing after 15 epoch, restarting , updating , deleting db dont helps

owner address 
0x337925eaba30d718f87ddc251c8c3314322f8e0bb87cf2e6c77cc4211b97e493

aptos_state_sync_version{type="applied_transaction_outputs"} 66202840
aptos_state_sync_version{type="executed_transactions"} 65533161
aptos_state_sync_version{type="synced"} 66202840
aptos_state_sync_version{type="synced_epoch"} 32

aptos_connections{direction="inbound",network_id="Validator",peer_id="337925ea",role_type="validator"} 209
aptos_connections{direction="outbound",network_id="Validator",peer_id="337925ea",role_type="validator"} 7

[log.txt](https://github.com/aptos-labs/aptos-ait3/files/9467023/log.txt)

**Comment by nodtechee** [comment]
[log.txt](https://github.com/aptos-labs/aptos-ait3/files/9467023/log.txt)

**Comment by nodtechee** [comment]
2h later

owner address
0x337925eaba30d718f87ddc251c8c3314322f8e0bb87cf2e6c77cc4211b97e493

# HELP aptos_state_sync_version The versions processed by the storage synchronizer operations
# TYPE aptos_state_sync_version gauge
aptos_state_sync_version{type="applied_transaction_outputs"} 67693498
aptos_state_sync_version{type="executed_transactions"} 65533161
aptos_state_sync_version{type="synced"} 67693498
aptos_state_sync_version{type="synced_epoch"} 32


aptos_connections{direction="inbound",network_id="Validator",peer_id="337925ea",role_type="validator"} 202
aptos_connections{direction="outbound",network_id="Validator",peer_id="337925ea",role_type="validator"} 16

[log.txt](https://github.com/aptos-labs/aptos-ait3/files/9467756/log.txt)

**Comment by nodtechee** [comment]
More logs

still no synhro 

aptos_state_sync_version{type="applied_transaction_outputs"} 98573721
aptos_state_sync_version{type="executed_transactions"} 92470970
aptos_state_sync_version{type="synced"} 98573721
aptos_state_sync_version{type="synced_epoch"} 40

aptos_connections{direction="inbound",network_id="Validator",peer_id="337925ea",role_type="validator"} 126
aptos_connections{direction="outbound",network_id="Validator",peer_id="337925ea",role_type="validator"} 96

aptos_consensus_current_round 8567
aptos_consensus_proposals_count 0


[log4.txt](https://github.com/aptos-labs/aptos-ait3/files/9474864/log4.txt)

**Comment by nodtechee** [comment]
info after update 8141a975f9e7d831e9699c58a83724ac9635d991

aptos_state_sync_version{type="applied_transaction_outputs"} 121544356
aptos_state_sync_version{type="executed_transactions"} 121482730
aptos_state_sync_version{type="synced"} 121544422
aptos_state_sync_version{type="synced_epoch"} 51

aptos_connections{direction="inbound",network_id="Validator",peer_id="337925ea",role_type="validator"} 213
aptos_connections{direction="outbound",network_id="Validator",peer_id="337925ea",role_type="validator"} 7

[log5.txt](https://github.com/aptos-labs/aptos-ait3/files/9480508/log5.txt)

**Comment by nodtechee** [comment]
info after update 26ed95ce4c8798743e7900bba566d29079af0a70


aptos_connections{direction="inbound",network_id="Validator",peer_id="337925ea",role_type="validator"} 221
aptos_connections{direction="inbound",network_id="vfn",peer_id="00000000",role_type="validator"} 1
aptos_connections{direction="outbound",network_id="Validator",peer_id="337925ea",role_type="validator"} 2
aptos_connections{direction="outbound",network_id="vfn",peer_id="00000000",role_type="validator"} 0

aptos_consensus_proposals_count 0

aptos_data_client_highest_advertised_data{data_type="ledger_infos"} 125854178
aptos_data_client_highest_advertised_data{data_type="states"} 125854178
aptos_data_client_highest_advertised_data{data_type="transaction_outputs"} 125854178
aptos_data_client_highest_advertised_data{data_type="transactions"} 125854178
aptos_state_sync_version{type="synced"} 125854176


[log6.txt](https://github.com/aptos-labs/aptos-ait3/files/9481839/log6.txt)

**Comment by nodtechee** [comment]
24 hours after update 88f936bf40a56768e2dac420e953a0307281c1ba
The node constantly freezes, one reboot does not always help, after the second reboot it starts to catch

aptos_connections{direction="inbound",network_id="Validator",peer_id="337925ea",role_type="validator"} 147
aptos_connections{direction="inbound",network_id="vfn",peer_id="00000000",role_type="validator"} 1
aptos_connections{direction="outbound",network_id="Validator",peer_id="337925ea",role_type="validator"} 69
aptos_connections{direction="outbound",network_id="vfn",peer_id="00000000",role_type="validator"} 0

aptos_consensus_proposals_count 0

aptos_data_client_highest_advertised_data{data_type="ledger_infos"} 166600179
aptos_data_client_highest_advertised_data{data_type="states"} 166600179
aptos_data_client_highest_advertised_data{data_type="transaction_outputs"} 166600179
aptos_data_client_highest_advertised_data{data_type="transactions"} 166600179
aptos_state_sync_version{type="synced"} 164238348


[log7.txt](https://github.com/aptos-labs/aptos-ait3/files/9485344/log7.txt)

**Comment by sherry-x** [comment]
Please upgrade to the latest of the testnet release and let us know if you have more issues.

**Comment by nodtechee** [comment]
2 hours after update 392dbd870a5dfc8e02503f8b2537903dc259baf1
Node still stuck and only reboot helps.


aptos_connections{direction="inbound",network_id="Validator",peer_id="337925ea",role_type="validator"} 214
aptos_connections{direction="inbound",network_id="vfn",peer_id="00000000",role_type="validator"} 1
aptos_connections{direction="outbound",network_id="Validator",peer_id="337925ea",role_type="validator"} 2
aptos_connections{direction="outbound",network_id="vfn",peer_id="00000000",role_type="validator"} 0

aptos_consensus_proposals_count 0

aptos_data_client_highest_advertised_data{data_type="ledger_infos"} 194420103
aptos_data_client_highest_advertised_data{data_type="states"} 194420103
aptos_data_client_highest_advertised_data{data_type="transaction_outputs"} 194420103
aptos_data_client_highest_advertised_data{data_type="transactions"} 194420103
aptos_state_sync_version{type="synced"} 194341809


[log8.txt](https://github.com/aptos-labs/aptos-ait3/files/9489107/log8.txt)
