### ISSUE TITLE
Both outbound connections and proposals count are "0"

### ISSUE THREAD

**Issue by ivanzrx** [aptos-labs/aptos-ait3#23]
1.
After I updated my validator image to "testnet_4219d75c57115805f0faf0ad07c17becf6580202", this happened. But I am not sure that update caused the issue. (I changed my validator image back to older one, and still getting the same issue).

<img width="749" alt="image" src="https://user-images.githubusercontent.com/38854208/187838118-b97cdaec-ca59-4df4-9a62-d4cb36203cc0.png">
<img width="755" alt="image" src="https://user-images.githubusercontent.com/38854208/187838195-6741775d-3459-456e-a724-c7bf9a315a99.png">

Log file :
[verse2-log.txt](https://github.com/aptos-labs/aptos-ait3/files/9467055/verse2-log.txt)

**Comment by sherry-x** [comment]
Please upgrade to the latest of the testnet release and let us know if you have more issues.
