### ISSUE TITLE
Staking form error TRANSACTION_EXPIRED

### ISSUE THREAD

**Issue by sorinenache83** [aptos-labs/aptos-ait3#3]
I used wallet version v0.1.8 on Chrome
I signed in with my wallet address: 0x1614c0510f246f089e63cb0dbf1c30529d6389d4b6591d209afd821065bf3541
I connected my wallet at https://explorer.devnet.aptos.dev/proposals/staking?network=ait3
Completed the form as follows:

Staking Amount: 100000000000000
Operator Address: 8835cbc88a6126b97e5df597b45bef22498738810ad381efdab7bb518b632432
Voter Address: 0x1614c0510f246f089e63cb0dbf1c30529d6389d4b6591d209afd821065bf3541

Hit Submit button then i get:

Failed with error message "Invalid transaction: Type: Validation Code: TRANSACTION_EXPIRED". Please try again.

**Comment by sherry-x** [comment]
Hey please try again and let us know if you can't get it to work

**Comment by sorinenache83** [comment]
Unfortunately I can no longer check since I continued the staking process in the console
BTW in the console worked just fine though
