### ISSUE TITLE
Node sync very very slow. Both of validator and fullnode.

### ISSUE THREAD

**Issue by m1zh** [aptos-labs/aptos-ait3#34]
This is my owner wallet: 0xb41568279f81fccc440bdbb807f68eb0cbdd494c74de5cccf545b0a47d890e93 .
My validator block synchronization is unable to keep up with the speed of block generation. 
<img width="794" alt="image" src="https://user-images.githubusercontent.com/105270340/187905545-a8fb255b-3981-45d1-a811-eda12f0cfdbb.png">
After 12 hours, node was synchronized only 65992300.  I have run on it latest version. And fullnode is in same situation.
<img width="897" alt="image" src="https://user-images.githubusercontent.com/105270340/187906289-d2d5f9d9-1891-4294-9491-1ba45c64e0a5.png">
<img width="870" alt="image" src="https://user-images.githubusercontent.com/105270340/187906452-b5eb9d5a-1462-4ac8-ad75-a352f4566e88.png">
Here is my validator log attachment.
[log.log](https://github.com/aptos-labs/aptos-ait3/files/9469495/log.log)

**Comment by JoshLind** [comment]
Hi @m1zh.
1. What hardware are you using? It looks like your node is bottlenecked on storage (i.e., reading/writing to storage is taking much longer than it should).
2. Also, can you please double check you're running the latest version of the testnet code?

**Comment by m1zh** [comment]
@JoshLind 
 I used 8c 32g and 300g ssd on GCP. I am very sure I am running the latest version of the testnet code. I use docker to build it. And my node works very well before the points reset. What can i do to fix it or is there any way to sync only the latest block for me to participate in consensus?
thanks!
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/105270340/187999692-47ee9196-f224-46bd-a85f-b2937ecba90f.png">
.

**Comment by m1zh** [comment]
![telegram-cloud-photo-size-5-6091627591833334166-y](https://user-images.githubusercontent.com/105270340/188036152-7949b860-0fdd-4166-b4d4-9c02439adaa6.jpg)
