### ISSUE TITLE
Failed to cast a vote

### ISSUE THREAD

**Issue by kj89** [aptos-labs/aptos-ait3#37]
When trying to cast a vote on a [proposal 0](https://explorer.devnet.aptos.dev/proposals/0) we receive an failed transaction error:
>Transaction [0xcb8ccdbe1ec0a89ce5e56b78eb4513e8d73688f8fbbfa303b79207af200ca2ac](https://explorer.devnet.aptos.dev/txn/0xcb8ccdbe1ec0a89ce5e56b78eb4513e8d73688f8fbbfa303b79207af200ca2ac) failed with "Execution failed in 0x1::stake::get_delegated_voter at code offset 1"

https://explorer.devnet.aptos.dev/txn/0xcb8ccdbe1ec0a89ce5e56b78eb4513e8d73688f8fbbfa303b79207af200ca2ac

![image](https://user-images.githubusercontent.com/50621007/188014160-a665a171-4b34-4707-b567-801dbbff17ee.png)

owner address: `0x57be1bdaf544178f3e754dd23f84c74a95785c694066f6c1d48762b8c888cbee`
voter address: `0x25a5ffaae84b3bb526ead2f28ae1f3e322dbe77f0013aad1d7be6e2a3e67614e`

**Comment by kj89** [comment]
![image](https://user-images.githubusercontent.com/50621007/188014498-0f9bcc7e-3718-4848-9a1f-266f8acc8ed9.png)

![image](https://user-images.githubusercontent.com/50621007/188014599-5c16f28e-de1a-4fa3-9120-97afecaf457e.png)

**Comment by justlstn** [comment]
<img width="2597" alt="image" src="https://user-images.githubusercontent.com/10776006/188015083-e446eb73-ca12-40c2-8f77-02fdf633ca33.png">

I've got another result.
Once I hit "Are you sure" -> "Agree" I've seen some requests with 404 status code with error code `transaction_not_found `

**Comment by justlstn** [comment]
Next attempt gave me another response

<img width="2600" alt="image" src="https://user-images.githubusercontent.com/10776006/188015524-9860f290-886c-4af9-be29-1753002311d4.png">

**Comment by Aderks** [comment]
Same issue

```
Transaction [0xf7c8db8e94e39a4da96c32e84f638c156e294e7807b52d08ea2ee15d01a1ecf7](https://explorer.devnet.aptos.dev/txn/0xf7c8db8e94e39a4da96c32e84f638c156e294e7807b52d08ea2ee15d01a1ecf7) failed with "Execution failed in 0x1::stake::get_delegated_voter at code offset 1"
```

**Comment by justlstn** [comment]
Well, I put wrong address in Owner Account Address. I put there Voter Address instead.
Anyway, once I put there Owner Address the transaction failed with another error

<img width="2599" alt="image" src="https://user-images.githubusercontent.com/10776006/188016250-2e6dea82-5532-4c20-a0ec-31fd8c795a87.png">

**Comment by justlstn** [comment]
<img width="2600" alt="image" src="https://user-images.githubusercontent.com/10776006/188016669-8b3554a7-dc87-40a6-810f-48ca53c9df34.png">

Based on the error message, I decided to increase lockup time on Staking page.
After that I was able to vote successfully.

**Comment by kj89** [comment]
Fixed by connecting voter wallet and then inputting owner address ;)
