### ISSUE TITLE
My node in list of AIT3-down-node, but node works, sometimes with successful transactions

### ISSUE THREAD

**Issue by mansurazaliev** [aptos-labs/aptos-ait3#43]
Hello! I've found my node `168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764` in list, but my validator-identity is correct (account address is my owner). 
Successful transactions:
```
"epoch": 37,
        "failed_proposal_count": 2,
        "max_potential_reward": 1598351194,
        "rewards_earned": 1278680955,
        "successful_proposal_count": 8,
        "validator_addr": "0x168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764",
        "voting_power": 100015718278584
```

Metrics: 
```
aptos_connections{direction="inbound",network_id="Validator",peer_id="168625c7",role_type="validator"} 149
aptos_connections{direction="inbound",network_id="vfn",peer_id="00000000",role_type="validator"} 1
aptos_connections{direction="outbound",network_id="Validator",peer_id="168625c7",role_type="validator"} 70
aptos_connections{direction="outbound",network_id="vfn",peer_id="00000000",role_type="validator"} 0
# HELP aptos_consensus_proposals_count Count of the block proposals sent by this validator since last restart (both primary and secondary)
# TYPE aptos_consensus_proposals_count counter
aptos_consensus_proposals_count 1
# HELP aptos_data_client_highest_advertised_data Gauge related to the highest advertised data
# TYPE aptos_data_client_highest_advertised_data gauge
aptos_data_client_highest_advertised_data{data_type="ledger_infos"} 106199825
aptos_data_client_highest_advertised_data{data_type="states"} 106199825
aptos_data_client_highest_advertised_data{data_type="transaction_outputs"} 106199825
aptos_data_client_highest_advertised_data{data_type="transactions"} 106199825
aptos_state_sync_version{type="synced"} 106199825
```
Hardware:
`16CPU/32GB/SSD/600Gbit`

Logs:

ait3-validator-1  | {"level":"ERROR","source":{"package":"network","file":"network/src/peer_manager/transport.rs:258"},"thread_name":"network-Validator","hostname":"d1b432822f75","timestamp":"2022-09-02T08:07:47.176493Z","message":"[validator,Validator,168625c7] Outbound connection failed for peer 1dd17527 at /ip4/167.235.26.108/tcp/6180/noise-ik/0xa6bf1ee023a3a51c554752e9db07d554a69c36e7938c5404d4e33917f9004a5c/handshake/0: Transport error: Connection refused (os error 111)","data":{"error":"Transport error: Connection refused (os error 111)","network_address":"/ip4/167.235.26.108/tcp/6180/noise-ik/0xa6bf1ee023a3a51c554752e9db07d554a69c36e7938c5404d4e33917f9004a5c/handshake/0","network_context":{"role":"validator","network_id":"Validator","peer_id":"168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764"},"remote_peer":"1dd17527c01616b252c9801366c158fbc0ff67b5ee76436e3cec04399d8de5d0"}}
ait3-validator-1  | {"level":"INFO","source":{"package":"network","file":"network/src/connectivity_manager/mod.rs:869"},"thread_name":"network-Validator","hostname":"d1b432822f75","timestamp":"2022-09-02T08:07:47.176546Z","message":"[validator,Validator,168625c7] Failed to connect to peer: 1dd17527 at address: /ip4/167.235.26.108/tcp/6180/noise-ik/0xa6bf1ee023a3a51c554752e9db07d554a69c36e7938c5404d4e33917f9004a5c/handshake/0; error: Transport error: Connection refused (os error 111)","data":{"error":"Transport error: Connection refused (os error 111)","network_address":"/ip4/167.235.26.108/tcp/6180/noise-ik/0xa6bf1ee023a3a51c554752e9db07d554a69c36e7938c5404d4e33917f9004a5c/handshake/0","network_context":{"role":"validator","network_id":"Validator","peer_id":"168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764"},"remote_peer":"1dd17527c01616b252c9801366c158fbc0ff67b5ee76436e3cec04399d8de5d0"}}
ait3-validator-1  | {"level":"ERROR","source":{"package":"network","file":"network/src/peer_manager/transport.rs:258"},"thread_name":"network-Validator","hostname":"d1b432822f75","timestamp":"2022-09-02T08:07:47.263696Z","message":"[validator,Validator,168625c7] Outbound connection failed for peer f1d4c93a at /ip4/18.116.40.89/tcp/6180/noise-ik/0xb08371db4a44697c5e5dbe6a9f9e4c1512aaa5a8c9ee62288ff942ec4f017f4a/handshake/0: Transport error: Connection refused (os error 111)","data":{"error":"Transport error: Connection refused (os error 111)","network_address":"/ip4/18.116.40.89/tcp/6180/noise-ik/0xb08371db4a44697c5e5dbe6a9f9e4c1512aaa5a8c9ee62288ff942ec4f017f4a/handshake/0","network_context":{"role":"validator","network_id":"Validator","peer_id":"168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764"},"remote_peer":"f1d4c93aa7e20e194e339a7d23c63b09a5501595870910c666213afea6ea1239"}}
ait3-validator-1  | {"level":"INFO","source":{"package":"network","file":"network/src/connectivity_manager/mod.rs:869"},"thread_name":"network-Validator","hostname":"d1b432822f75","timestamp":"2022-09-02T08:07:47.263749Z","message":"[validator,Validator,168625c7] Failed to connect to peer: f1d4c93a at address: /ip4/18.116.40.89/tcp/6180/noise-ik/0xb08371db4a44697c5e5dbe6a9f9e4c1512aaa5a8c9ee62288ff942ec4f017f4a/handshake/0; error: Transport error: Connection refused (os error 111)","data":{"error":"Transport error: Connection refused (os error 111)","network_address":"/ip4/18.116.40.89/tcp/6180/noise-ik/0xb08371db4a44697c5e5dbe6a9f9e4c1512aaa5a8c9ee62288ff942ec4f017f4a/handshake/0","network_context":{"role":"validator","network_id":"Validator","peer_id":"168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764"},"remote_peer":"f1d4c93aa7e20e194e339a7d23c63b09a5501595870910c666213afea6ea1239"}}
ait3-validator-1  | {"level":"ERROR","source":{"package":"network","file":"network/src/peer_manager/transport.rs:258"},"thread_name":"network-Validator","hostname":"d1b432822f75","timestamp":"2022-09-02T08:07:47.311615Z","message":"[validator,Validator,168625c7] Outbound connection failed for peer c3f2c9dc at /ip4/179.48.251.14/tcp/6180/noise-ik/0x33d0ec1fdd859302ef108c7521f77d028d188432555cb66b8e78354e92921352/handshake/0: Transport error: Connection refused (os error 111)","data":{"error":"Transport error: Connection refused (os error 111)","network_address":"/ip4/179.48.251.14/tcp/6180/noise-ik/0x33d0ec1fdd859302ef108c7521f77d028d188432555cb66b8e78354e92921352/handshake/0","network_context":{"role":"validator","network_id":"Validator","peer_id":"168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764"},"remote_peer":"c3f2c9dc502dbe9de4d3d3ee472fa679f578d978e53c1242a6906f894d435bd1"}}
ait3-validator-1  | {"level":"INFO","source":{"package":"network","file":"network/src/connectivity_manager/mod.rs:869"},"thread_name":"network-Validator","hostname":"d1b432822f75","timestamp":"2022-09-02T08:07:47.311666Z","message":"[validator,Validator,168625c7] Failed to connect to peer: c3f2c9dc at address: /ip4/179.48.251.14/tcp/6180/noise-ik/0x33d0ec1fdd859302ef108c7521f77d028d188432555cb66b8e78354e92921352/handshake/0; error: Transport error: Connection refused (os error 111)","data":{"error":"Transport error: Connection refused (os error 111)","network_address":"/ip4/179.48.251.14/tcp/6180/noise-ik/0x33d0ec1fdd859302ef108c7521f77d028d188432555cb66b8e78354e92921352/handshake/0","network_context":{"role":"validator","network_id":"Validator","peer_id":"168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764"},"remote_peer":"c3f2c9dc502dbe9de4d3d3ee472fa679f578d978e53c1242a6906f894d435bd1"}}
ait3-validator-1  | {"level":"INFO","source":{"package":"aptos_data_client","file":"state-sync/aptos-data-client/src/aptosnet/mod.rs:805"},"thread_name":"aptos-data-client","hostname":"d1b432822f75","timestamp":"2022-09-02T08:07:47.361290Z","data":{"event":"aggregate_summary","message":"Global data summary: AdvertisedData { Highest epoch ending ledger info, epoch: Some(45). Highest synced ledger info, epoch: Some(46), version: Some(106392861). Lowest transaction version: Some(0), Lowest transaction output version: Some(0), Lowest states version: Some(572224) }, OptimalChunkSizes { epoch_chunk_size: 100, state_chunk_size: 2000, transaction_chunk_size: 2000, transaction_output_chunk_size: 2000 }","name":"peer_states"}}
ait3-validator-1  | {"level":"ERROR","source":{"package":"network","file":"network/src/peer_manager/transport.rs:258"},"thread_name":"network-Validator","hostname":"d1b432822f75","timestamp":"2022-09-02T08:07:47.426358Z","message":"[validator,Validator,168625c7] Outbound connection failed for peer d16b8e15 at /ip4/66.94.104.49/tcp/6180/noise-ik/0x6dd21ff8d10578768466ccdc97b42e3acc557d016034d767171843090cde5376/handshake/0: Transport error: noise client: error reading server handshake response message, server probably rejected our handshake message: unexpected end of file","data":{"error":"Transport error: noise client: error reading server handshake response message, server probably rejected our handshake message: unexpected end of file","network_address":"/ip4/66.94.104.49/tcp/6180/noise-ik/0x6dd21ff8d10578768466ccdc97b42e3acc557d016034d767171843090cde5376/handshake/0","network_context":{"role":"validator","network_id":"Validator","peer_id":"168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764"},"remote_peer":"d16b8e15be631f0d22199f8b91b7338862fef9ee0a3af419477bd148a26cd2ff"}}
ait3-validator-1  | {"level":"INFO","source":{"package":"network","file":"network/src/connectivity_manager/mod.rs:869"},"thread_name":"network-Validator","hostname":"d1b432822f75","timestamp":"2022-09-02T08:07:47.426408Z","message":"[validator,Validator,168625c7] Failed to connect to peer: d16b8e15 at address: /ip4/66.94.104.49/tcp/6180/noise-ik/0x6dd21ff8d10578768466ccdc97b42e3acc557d016034d767171843090cde5376/handshake/0; error: Transport error: noise client: error reading server handshake response message, server probably rejected our handshake message: unexpected end of file","data":{"error":"Transport error: noise client: error reading server handshake response message, server probably rejected our handshake message: unexpected end of file","network_address":"/ip4/66.94.104.49/tcp/6180/noise-ik/0x6dd21ff8d10578768466ccdc97b42e3acc557d016034d767171843090cde5376/handshake/0","network_context":{"role":"validator","network_id":"Validator","peer_id":"168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764"},"remote_peer":"d16b8e15be631f0d22199f8b91b7338862fef9ee0a3af419477bd148a26cd2ff"}}
ait3-validator-1  | {"level":"ERROR","source":{"package":"network","file":"network/src/peer_manager/transport.rs:258"},"thread_name":"network-Validator","hostname":"d1b432822f75","timestamp":"2022-09-02T08:07:47.474680Z","message":"[validator,Validator,168625c7] Outbound connection failed for peer 3a9bcf67 at /ip4/34.134.37.36/tcp/6180/noise-ik/0xa5c30c777336df4716887460a63ff7fa441129f5ec6071c57d84ce61e15df625/handshake/0: Transport error: noise client: error reading server handshake response message, server probably rejected our handshake message: unexpected end of file","data":{"error":"Transport error: noise client: error reading server handshake response message, server probably rejected our handshake message: unexpected end of file","network_address":"/ip4/34.134.37.36/tcp/6180/noise-ik/0xa5c30c777336df4716887460a63ff7fa441129f5ec6071c57d84ce61e15df625/handshake/0","network_context":{"role":"validator","network_id":"Validator","peer_id":"168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764"},"remote_peer":"3a9bcf67be83271b05a2b3587e92b9a86834f7b281b35b636f9a2637398a9bf0"}}
ait3-validator-1  | {"level":"INFO","source":{"package":"network","file":"network/src/connectivity_manager/mod.rs:869"},"thread_name":"network-Validator","hostname":"d1b432822f75","timestamp":"2022-09-02T08:07:47.474749Z","message":"[validator,Validator,168625c7] Failed to connect to peer: 3a9bcf67 at address: /ip4/34.134.37.36/tcp/6180/noise-ik/0xa5c30c777336df4716887460a63ff7fa441129f5ec6071c57d84ce61e15df625/handshake/0; error: Transport error: noise client: error reading server handshake response message, server probably rejected our handshake message: unexpected end of file","data":{"error":"Transport error: noise client: error reading server handshake response message, server probably rejected our handshake message: unexpected end of file","network_address":"/ip4/34.134.37.36/tcp/6180/noise-ik/0xa5c30c777336df4716887460a63ff7fa441129f5ec6071c57d84ce61e15df625/handshake/0","network_context":{"role":"validator","network_id":"Validator","peer_id":"168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764"},"remote_peer":"3a9bcf67be83271b05a2b3587e92b9a86834f7b281b35b636f9a2637398a9bf0"}}
ait3-validator-1  | {"level":"INFO","source":{"package":"network","file":"network/src/protocols/rpc/mod.rs:593"},"thread_name":"network-Validator","hostname":"d1b432822f75","timestamp":"2022-09-02T08:07:47.687118Z","message":"[validator,Validator,168625c7] Received response for expired request_id 566 from 4c2cccd2. Discarding.","data":{"network_context":{"role":"validator","network_id":"Validator","peer_id":"168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764"},"remote_peer":"4c2cccd23aeec74fdd6a4309d77c15a382d1afad35fa0cd3f258be16be414789","request_id":566}}
ait3-validator-1  | {"level":"INFO","source":{"package":"network","file":"network/src/protocols/rpc/mod.rs:593"},"thread_name":"network-Validator","hostname":"d1b432822f75","timestamp":"2022-09-02T08:07:48.553903Z","message":"[validator,Validator,168625c7] Received response for expired request_id 783 from 873cc8a2. Discarding.","data":{"network_context":{"role":"validator","network_id":"Validator","peer_id":"168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764"},"remote_peer":"873cc8a29a8ad6afe1d13ffbaa512a91be22bb1b513ac4bd0b1077200d6be96f","request_id":783}}
ait3-validator-1  | {"level":"INFO","source":{"package":"network","file":"network/src/protocols/rpc/mod.rs:593"},"thread_name":"network-Validator","hostname":"d1b432822f75","timestamp":"2022-09-02T08:07:49.174188Z","message":"[validator,Validator,168625c7] Received response for expired request_id 568 from e35d670f. Discarding.","data":{"network_context":{"role":"validator","network_id":"Validator","peer_id":"168625c7aca6358fe94af73c52d65615c009683f372b5b0e7068d5f306aea764"},"remote_peer":"e35d670fa6481a8e490b33c0d33a2030831b996b5638e4ffc81c2864943bd6b4","request_id":568}}

**Comment by sherry-x** [comment]
You're good now
