### ISSUE TITLE
can't sync to 100% and also crushing after restart

### ISSUE THREAD

**Issue by vl8062** [aptos-labs/aptos-ait3#5]
Hi team,
@sherry-x 
My validator node is syncing to about 98% and stopping.
I tried to restart it 2 times and it crushed.
Internet bandwidth is 100/100.
Average usage was 8-10Mbps and it dropped when reached 98-99% of sync
Log is attached.
Thanks
[log1.txt](https://github.com/aptos-labs/aptos-ait3/files/9461855/log1.txt)
![traffic1](https://user-images.githubusercontent.com/109255546/187689648-7f875fee-6c96-4001-8e83-169037961a8a.JPG)

**Comment by vl8062** [comment]
I renamed Data folder and started the node. As expected, it's working now but syncing from scratch.
This or very similar issue was in AIT2 when my node was never reaching 100% of sync.
Also, is there a beta version or workaround to remove Data and DO not sync from scratch? This functionality was available in AIT2.
Thanks.

**Comment by sherry-x** [comment]
we're working on a doc for this, thanks!

**Comment by vl8062** [comment]
after deleting DB, it's still syncing from 0 when using commit 4219d75c57115805f0faf0ad07c17becf6580202
