### ISSUE TITLE
Aptos_consensus_proposals_count Not incrementing 

### ISSUE THREAD

**Issue by spasibotebe** [aptos-labs/aptos-ait3#56]
aptos_consensus_proposals_count Not incrementing

In epochs 125, 126, 127 I had successful_proposal_count (13, 20, 3)
After in the next epochs I got "failed_proposal_count": ~4, and "successful_proposal_count": null became

- I am using the latest docker update (testnet_392dbd870a5dfc8e02503f8b2537903dc259baf1)
- my node is connected to Aptos node

address: 0xd947abce2dab0abd4e0b705db96db38e0444c7347232ffed1b4d29cca74f86ef

Please help me!

![image](https://user-images.githubusercontent.com/9077313/188781321-4f368be4-65bd-4eac-b95b-e644b0d67874.png)

**Comment by JoshLind** [comment]
Thanks @spasibotebe. From what we can tell your node is often falling behind in consensus and using state sync to catch up. It appears to be lagging when in consensus mode. The storage latencies look a little high and the network latencies look somewhat higher than normal, too. Can you tell us what hardware you're using and where your node is deployed?

**Comment by spasibotebe** [comment]
Yes of course, 32 GB RAM, 8 vCPUs, 640 GB SSD

**Comment by sitalkedia** [comment]
Thanks for providing this information @spasibotebe . Would it be possible for you to try out 16 vCPUs instead, as per our hardware requirement - https://aptos.dev/nodes/ait/node-requirements#hardware-requirements. Also, can you provide your system CPU utilization metrics?

**Comment by spasibotebe** [comment]
![image](https://user-images.githubusercontent.com/9077313/188964839-2ac7ef46-4c49-42db-8073-38c50ef33f74.png)
Usually the CPU load is between 40% and 80%.
This is the maximum server on  "lightsail" (Amazon). After contacting Amazon support, it will take up to 5 days to consider my request.
 
I can try some more, maybe the internet channel is another problem.
If I change IP or change region, how critical is it?
Can you allow me to do this?

**Comment by spasibotebe** [comment]
![image](https://user-images.githubusercontent.com/9077313/188985523-ee48d0de-68d0-458d-ad2e-c07569842551.png)
Now the server load is 10% -20 percent for several hours.

**Comment by sitalkedia** [comment]
The process load has reduced because we have temporarily paused the traffic on the network and as a result, your node was able to catch up to the chain and is now able to successfully propose.  However, it might fall behind again once we start the load, so it is better if you can try with higher CPU and better bandwidth if that happens. 

![Screen Shot 2022-07-20 at 10 53 32 AM](https://user-images.githubusercontent.com/11507549/188997706-cdea6884-1f87-4e74-8816-33f106b58661.png)

**Comment by sitalkedia** [comment]
Closing this issue as it is resolved for now.

**Comment by spasibotebe** [comment]
![image](https://user-images.githubusercontent.com/9077313/189001193-81198901-6fd2-4c6c-b6bd-365324050f3d.png)
![image](https://user-images.githubusercontent.com/9077313/189008229-574f95fe-c430-4b18-901a-f54ee76942f6.png)

Sorry for my questions. Thanks for helping me figure it out.
Here is another graph of the load on the CPU. Perhaps my backlog is related to the Internet channel? Maybe test different node settings? Will this change something?
 
So in this region, I use the maximum amount of standard Amazon Lightsail resources at the moment.

With pleasure I will increase the server. But for this I need your permission to change the IP and (or) geolocation.
As much as possible? Can you give me permission?

Please answer this question, I want to be better. I need to understand how critical it is for you - changing the IP.

**Comment by sherry-x** [comment]
you can do that, see step 3 here https://aptos.dev/nodes/ait/connect-to-testnet#joining-validator-set
