### ISSUE TITLE
Problem with sync after last update (testnet_fe8e49af8f515c93914c2e6399f7e97c9b764446)

### ISSUE THREAD

**Issue by lenkazaiakova** [aptos-labs/aptos-ait3#64]
I updated my docker image to testnet_fe8e49af8f515c93914c2e6399f7e97c9b764446 and my node don't send proposals now.
Synchronization works unstable, it goes up for a while, then stuck and goes up again after some time. And that repeats.

Logs: 
[aptos_logs.txt](https://github.com/aptos-labs/aptos-ait3/files/9540184/aptos_logs.txt)

**Comment by ngocdoan** [comment]
same issue

**Comment by JoshLind** [comment]
Hi, please can you tell us your owner peer id?

**Comment by lenkazaiakova** [comment]
Fixed with re-syncing from scratch, but lost 30% of rewards perfomance during that new sync attempt.
