### ISSUE TITLE
buff/cache gets bigger and bigger until the node blocks

### ISSUE THREAD

**Issue by aptoschina** [aptos-labs/aptos-ait3#66]
My node is in South Africa, with 20 cores and 80g of memory. Any configuration node will get stuck after running for a period of time. Now I finally know the reason is that the buff / cache of memory will keep getting bigger until it occupies the whole memory. Then the node gets stuck and must be restarted.

**Comment by aptoschina** [comment]
![image](https://user-images.githubusercontent.com/104885688/189541906-1c78a3d4-a3ac-426c-99dd-6f97a9c7aaae.png)

**Comment by JoshLind** [comment]
Please tell us your owner peer id and send us some logs of your machine? Generally, memory usage is not a bad thing, unless something else is going on.

**Comment by aptoschina** [comment]
0x916926a34055b6402d115dbd5f6b8eeebad4ba70d775e0e6da864f3f919b9100

The log is normal, but sometimes the handshake failure error is displayed. I suspect that the network in remote areas is not good, so better configuration is needed.

**Comment by aptoschina** [comment]
logs   [https://www.aptoschina.com/log.txt](url)
