### ISSUE TITLE
Reward rate is 0% 

### ISSUE THREAD

**Issue by cryptobomj** [aptos-labs/aptos-ait3#7]
Hi all,

I installed my node yesterday morning before 12am UTC and in about a couple of hours it started to produce all the necessary stuff like 
`aptos_consensus_current_round` / `aptos_consensus_proposals_count` but i can see the proposals count barely increasing.
![image](https://user-images.githubusercontent.com/90379795/187756555-466ed781-764f-4522-bd7b-d415883259fb.png)
![image](https://user-images.githubusercontent.com/90379795/187756788-d512826e-b994-4dd8-ae08-bba12951d1e4.png)

Connected to the Aptos node alright and i got good amount of inbound / outbound connections 
![image](https://user-images.githubusercontent.com/90379795/187757341-f56b26d1-18bc-45a5-9daa-c94b3a6e3329.png)

And my stake keeps increasing! 
![image](https://user-images.githubusercontent.com/90379795/187757521-c8f0bb8c-6810-46a2-9f0b-57039b2a1d77.png)

Though at the moment the [[AIT-3 Validator Status] page](https://aptoslabs.com/leaderboard/it3) shows me 0% rewards
![image](https://user-images.githubusercontent.com/90379795/187758328-88741adc-aeda-466a-8834-6d693e030824.png)

And i just wonder what could be the issue and a possible fix?

Peace.

**Comment by pr-aptos** [comment]
We have reset our calculations from EPOCH 25 onwards -  you did not earn anything in epoch 25, hence the rewards rate went down to 0%. 

Here is the history JSON containing all the epoch perf. https://aptos-analytics-data-it3.s3.us-west-2.amazonaws.com/validator_epoch_history.json

No rewards in epoch 25 - 
<img width="933" alt="image" src="https://user-images.githubusercontent.com/104382863/187760521-83e9d9cc-b42f-4821-81d5-4ef7b5615486.png">

**Comment by cryptobomj** [comment]
Cool i see! 

So i can expect it to come back to normal in the future epochs? 

Assuming my stake keeps increasing.

**Comment by cryptobomj** [comment]
I can actually see that i am not receiving any rewards for 9 consecutive epochs:
![image](https://user-images.githubusercontent.com/90379795/187762381-13744276-9577-4bc3-84bc-5b2d44872266.png)

I guess this is not okay?

**Comment by sherry-x** [comment]
please check stats after epoch 25
