### ISSUE TITLE
My validator stopped syncing

### ISSUE THREAD

**Issue by pauloduartedf** [aptos-labs/aptos-ait3#8]
- My VPS for this AIT3 has currently the following specs:
8 vCPUs
32 GB RAM 
240 GB NVMe SSD
1Gbps connection
20 TB Transfer available
Ubuntu 20.04 (LTS) x64
Located in Helsinki/Finland

- I'm running from Docker (image tag - testnet_4219d75c57115805f0faf0ad07c17becf6580202)

- My validator can no longer sync even after restarting it, as a consequence it is also no longer voting or proposing.

- I am sharing my attached log.

[stdout.log](https://github.com/aptos-labs/aptos-ait3/files/9464278/stdout.log)

**Comment by JoshLind** [comment]
Thanks @pauloduartedf. Can you share your peer_id/owner address?

**Comment by JoshLind** [comment]
Looking at the logs, I see the validator calls into state sync, it syncs to the target and hands back and then the validator fails to retrieve blocks. Any ideas @zekun000?

**Comment by pauloduartedf** [comment]
> Thanks @pauloduartedf. Can you share your peer_id/owner address?

- peer_id - e8278487
- owner address - 0xe8278487a145eadfa3b07d7a711efe1606a7184045337b27259d6ab73e89aa5a

- updated log (810MB):
https://drive.google.com/file/d/1DEC07UhzTRid1iA098sBXuGTTHgYf62C/view?usp=sharing

**Comment by pauloduartedf** [comment]
- A few minutes ago I rescaled my validator to better spec so it was able to get in sync, also is voting and proposing again. The new specifications are:
16 vCPUs
32 GB RAM
360 GB NVMe SSD
1Gbps connection
20 TB Transfer available
Ubuntu 20.04 (LTS) x64
Located in Helsinki/Finland

**Comment by pauloduartedf** [comment]
- It seems the problem was solved.
![image](https://user-images.githubusercontent.com/36050535/187991489-a1dc9626-c9b6-4af1-ab47-bb174e9c1d2a.png)
