### ISSUE TITLE
aptos_consensus_proposals_count 0.   StakePool not increasing

### ISSUE THREAD

**Issue by dirikmihail** [aptos-labs/aptos-ait3#9]
OWNER ADDRESS  0x9eaa6c899597ca4d691cf453a1b0b17b534ed8fa91eac78a9e9bc0f457ee8cba

REWARDS PERFORMANCE 0 !!!!
aptos_consensus_current_round 1
aptos_consensus_proposals_count 0 
Number not increasing !!!

aptos_connections{direction="inbound",network_id="Validator",peer_id="9eaa6c89",role_type="validator"} 29
aptos_connections{direction="outbound",network_id="Validator",peer_id="9eaa6c89",role_type="validator"} 166

root@vmi847187:~# curl 127.0.0.1:9101/metrics 2> /dev/null | grep "aptos_network_peer_connected{.*remote_peer_id=\"f326fd30\".*}"
aptos_network_peer_connected{network_id="Validator",peer_id="9eaa6c89",remote_peer_id="f326fd30",role_type="validator"} 1

aptos_state_sync_version{type="applied_transaction_outputs"} 44965609
aptos_state_sync_version{type="executed_transactions"} 41414921
aptos_state_sync_version{type="synced"} 44965609
aptos_state_sync_version{type="synced_epoch"} 26
 
synchronized

StakePool not increasing

**Comment by sherry-x** [comment]
seems you're not synced yet. check latest version on explorer https://explorer.devnet.aptos.dev/?network=ait3

**Comment by dirikmihail** [comment]
> кажется, вы еще не синхронизированы. проверьте последнюю версию в проводнике https://explorer.devnet.aptos.dev/?network=ait3

Yes. Now synced.   But aptos_consensus_proposals_count 0 

aptos_consensus_current_round increasing

**Comment by dirikmihail** [comment]
[Log.txt](https://github.com/aptos-labs/aptos-ait3/files/9464606/Log.txt)

**Comment by dirikmihail** [comment]
Oh. Synchronization stopped again

**Comment by dirikmihail** [comment]
So already several times

**Comment by dirikmihail** [comment]
aptos_state_sync_version{type="applied_transaction_outputs"} 51237313
aptos_state_sync_version{type="executed_transactions"} 41567400
aptos_state_sync_version{type="synced"} 51389792
aptos_state_sync_version{type="synced_epoch"} 27

**Comment by dirikmihail** [comment]
Synchronization is constantly interrupted and then synchronized. And so all the time

**Comment by JoshLind** [comment]
Thanks @dirikmihail. Can you upload more logs? The ones you've sent are a little short 😄

**Comment by dirikmihail** [comment]
> Thanks @dirikmihail. Can you upload more logs? The ones you've sent are a little short 😄

😄  
Synchronization was left a few hours ago.  I am attaching the current logs. I will try to restart and then attach the logs again. Thanks @JoshLind

aptos_state_sync_version{type="applied_transaction_outputs"} 59468699
aptos_state_sync_version{type="executed_transactions"} 63153485
aptos_state_sync_version{type="synced"} 66202839
aptos_state_sync_version{type="synced_epoch"} 31
[Log.txt](https://github.com/aptos-labs/aptos-ait3/files/9468004/Log.txt)

**Comment by dirikmihail** [comment]
> Thanks @dirikmihail. Can you upload more logs? The ones you've sent are a little short 😄

Now synced. But it always lags behind.  
[Log.txt](https://github.com/aptos-labs/aptos-ait3/files/9468727/Log.txt)
